name: super_hero_app
description: SuperHeroApp It is an app which consumes from akabab/superhero-api project

publish_to: 'none'

version: 1.1.1+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.4
  dartz: ^0.10.1
  dio: ^4.0.6
  dio_cache_interceptor: ^3.2.7
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.5
  flutter_modular: ^4.5.1+1
  flutter_screenutil: ^5.5.2
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  mobx: ^2.0.7
  mocktail: ^0.3.0
  modal_bottom_sheet: ^2.0.1
  path_provider: ^2.0.9

dev_dependencies:
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2
  mobx_codegen: ^2.0.6

flutter:
  uses-material-design: true

  assets:
    - assets/