name: super_hero_app
description: SuperHeroApp It is an app which consumes from akabab/superhero-api project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.1
  dio: ^4.0.0
  dio_cache_interceptor: ^2.2.0
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_modular: ^3.1.1+1
  flutter_screenutil: ^5.0.0
  mocktail: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true